# O arquivo './desafios/desafio107-Tratamento_de_Erros.py' foi criado automaticamente